---
title: "homework4"
author: "zoy"
date: "2023-11-1"
output: html_document
---

```{r}
library(sf)
world <- st_read("C:\\casa\\gis\\gis_git\\week4\\homework_4\\data\\World_Countries_Generalized\\World_Countries_Generalized.shp")
```
```{r}
library(tidyverse)
library(janitor)
```
```{r}
HDR <- read_csv("C:\\casa\\gis\\gis_git\\week4\\homework_4\\data\\HDR21-22_Composite_indices_complete_time_series.csv" , locale = locale(encoding = "latin1"),
                       na = " ", skip=0)
```

```{r}
install.packages("countrycode")
library(countrycode)
HDIcols<- HDR %>%
  clean_names()%>%
  select(iso3, country, gii_2019, gii_2010)%>%
  mutate(difference=gii_2019-gii_2010)%>%
  #not needed here as we can now use the country name...but see below
  mutate(iso_code=countrycode(country, origin = 'country.name', destination = 'iso2c'))%>%
  mutate(iso_code2=countrycode(iso3, origin ='iso3c', destination = 'iso2c'))
```

```{r}
Join_HDI <- world %>% 
  clean_names() %>%
  left_join(., 
            HDIcols,
            # change to "aff_iso" = "iso_code"
            by = c("iso" = "iso_code"))

```

